### ISSUE TITLE
Proper OG and other metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/open.lbry.com#11]
@jessopb brought up a good point about sharing open.lbry.io URLs and preview images. It would be nice if the preview came from the thumbnail of the claim being shared. My initial thought was that this would require chainquery integration with open.lbry.io

**Comment by kauffj** [comment]
If open.lbry.com are our primary sharing URLs, this needs to be prioritized and match the behavior of lbry.tv.

lbry.tv currently does this in a somewhat hacky way, it's straight in server.js: https://github.com/lbryio/lbry-desktop/blob/master/src/platforms/web/server.js
