### ISSUE TITLE
Provide open graph and other social metadata for linking

### ISSUE THREAD

**Issue by kauffj** [lbryio/open.lbry.com#18]
Posting an open.lbry.io link on Facebook looks pretty bad. Can these pull in metadata from chainquery and use thumbnails from spee.ch (or the thumbnail metadata itself?)?

**Comment by tzarebczan** [comment]
Same as https://github.com/lbryio/open.lbry.io/issues/11 ?

**Comment by kauffj** [comment]
I managed to create a duplicate issue when there are 3 total open issues. That's talent.
