### ISSUE TITLE
Make redirect intelligent enough to selectively redirect to appropriate locations

### ISSUE THREAD

**Issue by jessopb** [lbryio/open.lbry.com#19]
If IOS, there is no reason to redirect to app store.
If Android, go to app store or app.
If App is installed, go there.
If App is not installed, go to lbry.tv.

**Comment by jessopb** [comment]
After discussion with @kauffj , we decided to have the redirect page offer two options with a ~5 second pausable countdown. On selecting a "remember this setting" on a redirect to app or lbry.tv, that setting will be saved in localstorage for the user and the countdown significantly shortened. The user can return to open.lbry.com to modify their preferences.
@seanyesmunt @akinwale @tzarebczan comments on redirecting to app store?

**Comment by kauffj** [comment]
@jessopb what's blocking deploy of this?
