### ISSUE TITLE
Add ability to create a short URL based on input

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/open.lbry.com#3]
I.e. instead of sharing open.lbry.io/squad-9-7-crazy-comeback-ft-karmakut you'd have an option to create a link like open.lbry.io/xYXaQ 

I long time ago I thought of a URL shortening service, so I grabbed lbry.sh  (lbry short)- we can use that if it makes more sense.

**Comment by lyoshenka** [comment]
This would be a significant change. Right now this whole thing is 10 lines of php and 5 lines of JS. Doing short URLs would involve adding a database and a bunch of coding. Nothing major (prolly a day of work total), but a lot bigger than what this is now.

That said, there are a bunch of off-the-shelf url shorteners out there. We could copy one and run it at lbry.sh and just have all the links point at open.lbry.io.

**Comment by NetOpWibby** [comment]
So is the solution here to create a new repo for this issue? For the URL shortener? How do databases run on Heroku?

_I'm assuming that's what we'll be using._

**Comment by NetOpWibby** [comment]
Since my last comment I've spoken with Jeremy and this issue will never get implemented due to LBRY Web's impending existence.
