### ISSUE TITLE
redirect fails on channel + claim (due to / encoding)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/open.lbry.com#4]
Entering something like `@bluedrake42/squad-9-7-crazy-comeback-ft-karmakut` causes this error: 
`The requested URL /@bluedrake42/squad-9-7-crazy-comeback-ft-karmakut was not found on this server.`

It might have something to do with the URL encoding, because if you change the URL manually to https://open.lbry.io/%40bluedrake42/squad-9-7-crazy-comeback-ft-karmakut it works.

**Comment by lyoshenka** [comment]
fixed in 268b5ca
