### ISSUE TITLE
redirect to get page if LBRY not installed?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/open.lbry.com#5]
This is what I'm seeing when LBRY is not installed on a PC, and a user goes to https://open.lbry.io/test:
IE doesn't do anything

Chrome says open URL:lbry?, then nothing happens.

Firefox has a launch application dialog with lbry, but nothing happens when you click "Open Link".

Is there any way for us to tell if LBRY is not installed ((uri not registered?) and re-direct the user to the get page (or some FAQ)?

**Comment by lyoshenka** [comment]
based on my brief googling, this is only possible on mobile

**Comment by tzarebczan** [comment]
Jeremy found this, not sure if it's useful here: 
https://github.com/ismailhabib/custom-protocol-detection

**Comment by kauffj** [comment]
@lyoshenka my brief googling is better than yours :stuck_out_tongue:

**Comment by tzarebczan** [comment]
I think what we have right now is a good enough - we show them a link to the get page is LBRY is not installed.
