### ISSUE TITLE
add our google analytics standard event to this page

### ISSUE THREAD

**Issue by finer9** [lbryio/open.lbry.com#6]
I need to be able to see incoming traffic to open.lbry.io - not an event/conversion but a standard GA tag

**Comment by kauffj** [comment]
Who wrote this originally? Guessing we'll ask @maximest-pierre to try this if this project is unowned.

(Nothing to do until this makes it into a sprint though, Maxime)

**Comment by finer9** [comment]
@robvsmith Do you think this has value still?  The idea is we could track how many click on the open. links more directly in Google Analytics

**Comment by kauffj** [comment]
Blocked by https://github.com/lbryio/open.lbry.io/issues/12
