### ISSUE TITLE
Add Directions

### ISSUE THREAD

**Issue by jamesbiller** [lbryio/open.lbry.com#7]
We need people going here to know how to use it. 

Have a message like:

"To create a hyperlink that opens in LBRY simply copy & paste the location of the file in lbry:// into the box. (Do not include lbry://)

For example, lbry://LBRYCreditsAcceptedHere will open as https://open.lbry.io/LBRYCreditsAcceptedHere"

**Comment by kauffj** [comment]
@jamesbiller if you're feeling bold try editing this file

https://github.com/lbryio/webredirect/blob/master/web/homepage.html

**Comment by jamesbiller** [comment]
@kauffj just proposed the change!

**Comment by tzarebczan** [comment]
@jamesbiller I don't see the changes...the help text could still be useful.
